//===-- SampleSubtarget.h - Define Subtarget for the Sample ----*- C++ -*--===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the Sample specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_TARGET_SAMPLE_SUBTARGET_H
#define LLVM_TARGET_SAMPLE_SUBTARGET_H

#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "SampleGenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class SampleSubtarget : public SampleGenSubtargetInfo {
  virtual void anchor() {};
  bool ExtendedInsts;
public:
  /// This constructor initializes the data members to match that
  /// of the specified triple.
  SampleSubtarget(const std::string &TT, const std::string &CPU,
                  const std::string &FS);

  // Autogenerated by tblgen.
  /// ParseSubtargetFeatures - Parses features string setting specified
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef FS);
};
} // End llvm namespace

#endif  // LLVM_TARGET_SAMPLE_SUBTARGET_H
